/*
 * File: app/view/ui/DomainsTreePanel.js
 * Date: Thu Feb 09 2012 16:52:45 GMT+0400 (Ìîñêîâñêîå âðåìÿ (çèìà))
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PetroRes.view.ui.DomainsTreePanel', {
    extend: 'Ext.tree.Panel',

    title: 'Domains',
    rootVisible: false,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            viewConfig: {
                plugins: { ptype: 'treeviewdragdrop' }
            },
            columns: [
                {
                    xtype: 'treecolumn',
                    dataIndex: 'name',
                    editor: 'textfield',
                    flex: 15,
                    text: 'Domain'
                }/*,
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'level',
                    editor: 'textfield',
                    flex: 4,
                    text: 'Level'
                }*/
            ]
        });

        me.callParent(arguments);
    }
});