/*
 * File: app/view/ui/MainWindow.js
 * Date: Thu Feb 09 2012 16:52:45 GMT+0400 (Ìîñêîâñêîå âðåìÿ (çèìà))
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PetroRes.view.ui.MainWindow', {
    extend: 'Ext.window.Window',

    layout: {
        type: 'fit'
    },
    title: 'Petroresource Documents System',

    initComponent: function() {
        var me = this;

        me.callParent(arguments);
    }
});