/*
 * File: app/view/DomainForm.js
 * Date: Wed Feb 08 2012 17:30:08 GMT+0400 (Ìîñêîâñêîå âðåìÿ (çèìà))
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('PetroRes.view.AuthorForm', {
    extend: 'Ext.form.Panel',

    bodyPadding: 10,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
            {
                xtype: 'textfield',
                name: 'login',
                fieldLabel: 'Login',
                anchor: '100%'
            },
            {
                xtype: 'textfield',
                name: 'name',
                fieldLabel: 'Name',
                anchor: '100%'
            },
            {
                xtype: 'textfield',
                name: 'shortName',
                fieldLabel: 'Short Name',
                anchor: '100%'
            },
            {
                xtype: 'textfield',
                name: 'description',
                fieldLabel: 'Bio',
                anchor: '100%'
            },
            {
                xtype: 'textfield',
                name: 'contact',
                fieldLabel: 'Contact',
                anchor: '100%'
            },
            {
                xtype: 'textfield',
                name: 'email',
                fieldLabel: 'E-mails',
                anchor: '100%'
            },
            {
                xtype: 'textfield',
                name: 'phone',
                fieldLabel: 'Phones',
                anchor: '100%'
            },
            {
                xtype: 'checkbox',
                name: 'isInternal',
                fieldLabel: 'Internal',
                anchor: '100%'
            }, {
                xtype: 'combo',
                name: 'organization',
                fieldLabel: 'Organization',
                store: 'OrganizationsJsonStore',
                displayField: 'name',
                listeners: {
                    select: function(){
                        this.value=this.valueModels[
                            0
                        ].raw;
                    }
                }
            }
            
            ],
            
            buttons: [{
                text: 'Save',
                handler: function() {
                    var form = this.up('form').getForm();
                    if(form.isValid()){
                        form.updateRecord(form.getRecord());
                        form.getRecord().save();
                        me.up('window').close();
                    }
                }
            }]
            
        });

        me.callParent(arguments);
    }
});