/*
 * File: app/view/DomainForm.js
 * Date: Wed Feb 08 2012 17:30:08 GMT+0400 (Ìîñêîâñêîå âðåìÿ (çèìà))
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('PetroRes.view.DomainForm', {
    extend: 'Ext.form.Panel',

    bodyPadding: 10,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
            {
                xtype: 'textfield',
                name: 'name',
                fieldLabel: 'Name',
                anchor: '100%'
            },
            {
                xtype: 'textfield',
                name: 'fullName',
                fieldLabel: 'Full Name',
                anchor: '100%'
            },
            {
                xtype: 'textfield',
                name: 'pathPart',
                fieldLabel: 'Folder',
                anchor: '100%'
            },
            {
                xtype: 'combobox',
                name: 'site',
                fieldLabel: 'Project',
                displayField: 'name',
                store: 'SitesJsonStore',
                anchor: '100%'
                ,
                listeners: {
                    select: function(combo, records){
                        //console.log(this.valueModels);
                        //console.log(records);
                        this.value=records[0].data;
                    }
                }
            },

            {
                xtype: 'combobox',
                name: 'well',
                fieldLabel: 'Well',
                displayField: 'name',
                store: 'WellsJsonStore',
                anchor: '100%'
                ,
                listeners: {
                    select: function(combo, records){
                        this.value=records[0].data;
                    }
                }
            },

            {
                xtype: 'combobox',
                name: 'typeOfWork',
                fieldLabel: 'Type Of Work',
                displayField: 'name',
                store: 'TypesOfWorkJsonStore',
                anchor: '100%'
                ,
                listeners: {
                    select: function(combo, records){
                        this.value=records[0].data;
                    }
                }
            },

            {
                xtype: 'combobox',
                name: 'workProcess',
                fieldLabel: 'Work Process',
                displayField: 'name',
                store: 'WorkProcessesJsonStore',
                anchor: '100%'
                ,
                listeners: {
                    select: function(combo, records){
                        this.value=records[0].data;
                    }
                }
            }
            ]
        });

        me.callParent(arguments);
    }
});