/*
 * File: app/view/SitesGridPanel.js
 * Date: Thu Jan 12 2012 18:08:08 GMT+0400 (Ìîñêîâñêîå âðåìÿ (çèìà))
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('PetroRes.view.SitesGridPanel', {
    extend: 'PetroRes.view.ui.SitesGridPanel',

    initComponent: function() {
        var me = this;
        me.callParent(arguments);
        
        var proxy = me.store.getProxy();
        
        Ext.apply(proxy.actionMethods, {
            update: 'PUT',
            create: 'POST',
            destroy: 'DELETE'
        });
        
        /*var oldWrite = proxy.writer.write;
        proxy.writer.write = function(request){
            if(request.action === 'destroy' && request.records.length == 1){
                var quotePos = request.url.indexOf('?');
                request.url = 
                    request.url.substring(0, quotePos) + "/" + request.records[0].get('id') + 
                    request.url.substring(quotePos);
            }
            var ret = oldWrite.call(proxy.writer, request);
            return ret;
        };*/

        me.addButton = me.dockedItems.getByKey('pagingToolBar').items.getByKey('addButton')
        
        me.headerCt.insert(0, {
            xtype:'actioncolumn',
            flex:1,
            items: [{
                icon: 'lib/ext41/examples/restful/images/delete.png',
                tooltip: 'Delete',
                handler: function(grid, rowIndex, colIndex) {
                    grid.store.removeAt(rowIndex);
                }
            }]
        });

        for (var i in me.plugins){
            if(me.plugins[i]['$className']==='Ext.grid.plugin.RowEditing'){
                me.editorPlugin = me.plugins[i];
                me.editorPlugin.on('canceledit', function(){
                    if(me.editorPlugin.startedPetroObjectAdd == true){
                        me.store.autoSync = false;
                        me.editorPlugin.startedPetroObjectAdd = false;
                        me.store.removeAt(0);
                        me.store.autoSync = true;
                    }
                });
                me.addButton.on('click', function(){
                    me.editorPlugin.cancelEdit();
                    me.store.autoSync = false;

                    me.store.insert(0, {});
                    me.editorPlugin.startEdit(0, 0);            
                    me.editorPlugin.startedPetroObjectAdd = true;            
                    me.store.autoSync = true;
                });
                
                break;
            }
        }

        /*proxy.afterRequest = function(request){
            if(request.action === 'create' && request.records.length==1){
                var uriCame = request.operation.response.getResponseHeader('location');
                if(uriCame){
                    me.store.autoSync = false;
                    var ch = uriCame.indexOf('?');
                    var uri;
                    if(ch>=0)
                        uri = uriCame.substring(0, ch);
                    else
                        uri = uriCame;
                    if(uri.charAt(uri.length-1)==='/')
                        uri = uri.substring(0, uri.length-1);
                    var id = parseInt(uri.substring(uri.lastIndexOf('/')+1));

                    request.records[0].set('id', id);
                    request.records[0].modified.id = undefined;
                    request.records[0].dirty = false;
                    
                    me.store.autoSync = true;
                }
            }
        };*/
    }
});
