/*
 * File: app/store/DocumentsJsonStore.js
 * Date: Thu Feb 09 2012 16:52:45 GMT+0400 (Ìîñêîâñêîå âðåìÿ (çèìà))
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PetroRes.store.DocumentsJsonStore', {
    extend: 'Ext.data.Store',

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            autoSync: true,
            storeId: 'DocumentsJsonStore',
            //buffered: true,
            pageSize: 10,
            //leadingBufferZone: 20,
            remoteSort: true,
            proxy: {
                type: 'ajax',
                url: 'rest/documents',
                headers: {
                    Accept: 'application/json'
                },
                reader: {
                    type: 'json',
                    idProperty: 'id',
                    root: 'documents'
                }
            },
            /*associations:[
                {
                    type: 'hasMany',
                    model: Ext.getStore('SitesJsonStore').getProxy().getModel(),  
                    name: 'site'
                },
                {
                    type: 'hasOne',
                    model: Ext.getStore('ClassificationsJsonStore').getProxy().getModel(),  
                    name: 'classification'
                }
            ],*/
            fields: [
                {
                    name: 'id',
                    type: 'int'
                },
                {
                    name: 'year'
                },
                {
                    name: 'number'
                },
                {
                    name: 'archiveNumber'
                },
                {
                    name: 'title'
                },
                {
                    name: 'fullTitle'
                },
                {
                    name: 'type'
                },
                {
                    name: 'comment'
                },
                {
                    name: 'originationDetails'
                },
                {
                    name: 'limitationDetails'
                },
                {
                    name: 'originationDate',
                    type: 'date'
                },
                {
                    name: 'approvalDate',
                    type: 'date'
                },
                {
                    name: 'registrationDate',
                    type: 'date'
                },
                {
                    name: 'placementDate',
                    type: 'date'
                },
                {
                    name: 'placer'
                },
                {
                    name: 'updateDate',
                    type: 'date'
                },
                {
                    name: 'pageCount'
                },
                {
                    name: 'geometryType'
                },
                {
                    name: 'scale'
                },
                {
                    name: 'resolution'
                },
                {
                    name: 'projection'
                },
                {
                    name: 'periodicity'
                },
                {
                    name: 'classification'
                },
                {
                    name: 'site'
                },
                {
                    name: 'stage'
                },
                {
                    name: 'words'
                },
                {
                    name: 'authors'
                },
                {
                    name: 'geoObjects'
                },
                {
                    name: 'domain'
                },
                {
                    name: 'files'
                },
                {
                    name: 'typeOfWork'
                },
                {
                    name: 'workProcess'
                }
                
            ]
        }, cfg)]);
    }
});