/*
 * File: app/store/DomainsJsonTreeStore.js
 * Date: Thu Feb 09 2012 16:52:45 GMT+0400 (Ìîñêîâñêîå âðåìÿ (çèìà))
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PetroRes.store.DomainsJsonTreeStore', {
    extend: 'Ext.data.TreeStore',

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
                
            root: {
                    expanded: true,
                    id: petroresConfig.domainRootId,
                    level: 0,
                    parentId: null
            },
                
            clearOnLoad: false,
            autoLoad: true,
            autoSync: true,
            storeId: 'DomainsJsonTreeStore',
            nodeParam: 'parent',
            proxy: {
                type: 'ajax',
                url: 'rest/domains',
                headers: {
                    Accept: 'application/json'
                },
                reader: {
                    type: 'json',
                    idProperty: 'id',
                    root: 'domains'
                }
            },
            fields: [
                {
                    name: 'id',
                    type: 'int'
                },
                {
                    name: 'name'
                },
                {
                    name: 'fullName'
                },
                {
                    name: 'parent'
                },
                {
                    name: 'level',
                    type: 'int'
                },
                {
                    name: 'pathPart'
                },
                {
                    name: 'site'
                },
                {
                    name: 'well'
                },
                {
                    name: 'typeOfWork'
                },
                {
                    name: 'workProcess'
                }
            ]
        }, cfg)]);
    }
});