/*
 * File: app/store/FilesJsonStore.js
 * Date: Thu Feb 09 2012 16:52:45 GMT+0400 (Ìîñêîâñêîå âðåìÿ (çèìà))
 *
 * This file was generated by Ext Designer version 1.2.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PetroRes.store.FilesJsonStore', {
    extend: 'Ext.data.Store',

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            autoSync: true,
            storeId: 'FilesJsonStore',
            //buffered: true,
            pageSize: 10,
            remoteSort: true,
            proxy: {
                type: 'ajax',
                url: 'rest/files',
                headers: {
                    Accept: 'application/json'
                },
                reader: {
                    type: 'json',
                    idProperty: 'id',
                    root: 'files'
                }
            },
            fields: [
                {
                    name: 'id',
                    type: 'int'
                },
                {
                    name: 'document'
                },
                {
                    name: 'path'
                },
                {
                    name: 'mimeType'
                },
                {
                    name: 'isDeleted',
                    type: 'boolean'
                }
            ]
        }, cfg)]);
    }
});